### ISSUE TITLE
ToDo list

### ISSUE THREAD

**Issue by sarbbottam** [sarbbottam/web-accessibility#1]
- [ ] beef up README
- [ ] add examples on aria live
- [ ] add examples on modal a11y
- [ ] display corresponding code next to the example
- [ ] beautify the index.html
- [ ] add site navigation or beard crumbs to the example pages
